# Generated by Django 3.1.7 on 2021-03-14 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('featured', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProducFeatured',
            new_name='ProductFeatured',
        ),
        migrations.AlterModelOptions(
            name='productfeatured',
            options={'verbose_name_plural': 'Products Featurd'},
        ),
    ]
