# Generated by Django 3.1.7 on 2021-03-15 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('featured', '0002_auto_20210314_1920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productfeatured',
            options={'verbose_name_plural': 'Products Featured'},
        ),
    ]
