# Generated by Django 3.1.7 on 2021-03-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.AddField(
            model_name='orders',
            name='items_ordered',
            field=models.ManyToManyField(to='orders.OrderItem'),
        ),
    ]
