# Generated by Django 3.1.7 on 2021-03-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210324_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='items_ordered',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ManyToManyField(to='orders.Orders'),
        ),
    ]
