# Generated by Django 3.1.7 on 2021-03-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20210324_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ManyToManyField(related_name='items_ordered', to='orders.Orders'),
        ),
    ]
