# Generated by Django 3.1.7 on 2021-03-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20210324_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.AddField(
            model_name='orders',
            name='items_ordered',
            field=models.ManyToManyField(related_name='items_ordered', to='orders.OrderItem'),
        ),
    ]
