# Generated by Django 3.1.7 on 2021-03-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20210324_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
