# Generated by Django 3.1.7 on 2021-03-14 14:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('drink', models.CharField(max_length=150)),
                ('cover_picture', models.ImageField(upload_to='covers')),
                ('category', models.CharField(choices=[('Wines', 'Wines'), ('Spirits', 'Spirits'), ('Energy Drinks', 'Energy Drinks'), ('Water', 'Water'), ('Sodas', 'Sodas')], max_length=150)),
                ('price', models.PositiveIntegerField()),
                ('previous_price', models.PositiveIntegerField(blank=True, null=True)),
                ('discount', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Drinks',
            },
        ),
    ]
