# Generated by Django 3.1.7 on 2021-03-14 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drink', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drink',
            old_name='drink',
            new_name='name',
        ),
    ]
