# Generated by Django 3.1.7 on 2021-03-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drink', '0002_auto_20210314_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='brand',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='drink',
            name='category',
            field=models.CharField(choices=[('Wines and Spirits', 'Wines and Spirits'), ('Energy Drinks', 'Energy Drinks'), ('Soft Drinks', 'Soft Drinks'), ('Water', 'Water')], max_length=150),
        ),
    ]
