# Generated by Django 3.1.7 on 2021-03-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drink', '0003_auto_20210315_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='brand',
            field=models.CharField(blank=True, help_text='input a company,brand or group that made the product', max_length=150, null=True),
        ),
    ]
