# Generated by Django 3.1.7 on 2021-03-15 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drink', '0004_auto_20210315_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(help_text='Choose a town or city you live in', max_length=150)),
                ('area', models.CharField(help_text='Choose correct location you live in that town', max_length=150)),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drink.drink')),
            ],
            options={
                'verbose_name_plural': 'Locations',
            },
        ),
    ]
