# Generated by Django 3.1.7 on 2021-03-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drink', '0005_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name_plural': 'Location to be delivered to'},
        ),
        migrations.AddField(
            model_name='location',
            name='delivered',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
