# Generated by Django 3.1.7 on 2021-03-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drink', '0006_auto_20210315_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='delivered',
        ),
        migrations.AddField(
            model_name='drink',
            name='delivered',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
