# Generated by Django 3.1.7 on 2021-03-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drink', '0009_auto_20210315_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='delivered',
        ),
        migrations.AddField(
            model_name='order',
            name='delivered',
            field=models.BooleanField(blank=True, help_text='*Do not fill this field*', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.PositiveIntegerField(blank=True, help_text='*Do not fill this field*', null=True),
        ),
    ]
