# Generated by Django 3.1.7 on 2021-03-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drink', '0011_auto_20210315_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivered',
            field=models.BooleanField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', help_text='*Fill this field when the delivery has been made*', null=True),
        ),
    ]
