# Generated by Django 3.1.7 on 2021-03-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drink', '0015_auto_20210315_1645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-time_ordered'], 'verbose_name_plural': 'Orders'},
        ),
        migrations.AddField(
            model_name='order',
            name='time_ordered',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
