# Generated by Django 3.1.7 on 2021-03-15 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drink', '0017_auto_20210315_1703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Orders'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='time_ordered',
            new_name='order_date',
        ),
    ]
