# Generated by Django 3.1.7 on 2021-03-15 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drink', '0021_order_kim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='kim',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(),
        ),
    ]
