# Generated by Django 3.1.7 on 2021-03-15 21:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('drink', '0022_auto_20210316_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 15, 21, 27, 36, 502545, tzinfo=utc)),
        ),
    ]
