# Generated by Django 3.1.7 on 2021-03-16 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drink', '0024_auto_20210316_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='drink',
        ),
        migrations.AddField(
            model_name='drink',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drinks_ordered', to='drink.order'),
        ),
    ]
