# Generated by Django 3.1.7 on 2021-03-16 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drink', '0025_auto_20210316_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='drink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='drink.drink'),
        ),
    ]
