# Generated by Django 3.1.7 on 2021-03-18 20:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('drink', '0026_auto_20210316_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drink',
            options={'ordering': [], 'verbose_name_plural': 'Drinks'},
        ),
        migrations.AddField(
            model_name='drink',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
