# Generated by Django 3.1.7 on 2021-03-22 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drink', '0027_auto_20210318_2330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drink',
            options={'ordering': ['-date_added'], 'verbose_name_plural': 'Drinks'},
        ),
    ]
