# Generated by Django 3.1.7 on 2021-04-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drink', '0029_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='variation',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Payment on delivery', 'payment on delivery'), ('Pay before delivery', 'Pay before delivery')], max_length=150, null=True),
        ),
    ]
