# Generated by Django 3.1.7 on 2021-04-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drink', '0031_order_total_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='ordered_by',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='delivery_method',
            new_name='delivery',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(blank=True, choices=[('Payment on delivery', 'Payment on delivery'), ('Pay before delivery', 'Pay before delivery')], max_length=150, null=True),
        ),
    ]
